### ISSUE TITLE
.NET 7 Reverse Engineer OnModelCreating

### ISSUE THREAD

**Issue by FeraMJ** [ErikEJ/EFCorePowerTools#1521]
Describe what is not working as expected.

### Provide steps to reproduce

Please include a **complete** description or project that I can redo/run to reproduce the issue.

### Provide technical details

- EF Core version in use: (e.g. EF Core 6)

- Is Handlebars used: no/yes

- Is .dacpac used: no/yes

- EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)

- Database engine: (SQL Server, Azure SQL, Postgres, Oracle, Firebird, SQLite, MySQL)

- Visual Studio version: (e.g. Visual Studio 2022)

**Comment by FeraMJ** [comment]
Reverse Engineer using the EF Core 7 (preview) template does not add the calls to OnModelCreatingGeneratedFunctions and OnModelCreatingGeneratedProcedures. Screenshot attached.

![2022-09-17_9-40-37](https://user-images.githubusercontent.com/113781143/190860416-892f9429-0f79-41dd-841b-a28f62f81c2a.png)

**Comment by ErikEJ** [comment]
What do you mean by "template" - the .t4 templates?

**Comment by FeraMJ** [comment]
Hi Erik. Thank you for sharing EF Core Power Tools. It's an excellent utility and a real time saver. Perhaps template is the wrong word, but this is what I'm referring to:

![image](https://user-images.githubusercontent.com/113781143/190861168-d65e78b0-ff33-4800-bc77-d9714669f04f.png)

**Comment by ErikEJ** [comment]
Fixed in latest daily build

**Comment by ErikEJ** [comment]
Must be build .1142 or newer - please let me know if it works for you

**Comment by FeraMJ** [comment]
Issue resolved. Thank you for the superfast resolution! Just a very small cosmetic issue remains. The new lines have an extra tab.

![image](https://user-images.githubusercontent.com/113781143/190863019-6d0baf7f-361c-4a65-a491-5004a53092c0.png)

**Comment by ErikEJ** [comment]
Formatting fixed in latest daily.

I would be very grateful for a rating or review on Visual Studio Marketplace.

**Comment by FeraMJ** [comment]
Would be happy to. Thanks again.

**Comment by ErikEJ** [comment]
I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)
