### ISSUE TITLE
Error in Scaffolding Scalar Function using EF Core 6

### ISSUE THREAD

**Issue by fshahin90** [ErikEJ/EFCorePowerTools#1699]
- EF Version: EF Core 6
- Extension Version: 2.5.1287
I get the following Error when scaffolding functions.
 Error:
```
System.InvalidOperationException: Reverse engineer error: 
System.ArgumentException: The string argument 'name' cannot be empty.
   at string Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(string value, string parameterName)
   at string Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Identifier(string name, ICollection<string> scope, bool? capitalize)
   at void RevEng.Core.Functions.SqlServerFunctionScaffolder.GenerateFunctionStub(Routine function, RoutineModel model)+(ModuleParameter p) => { } in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/Functions/SqlServerFunctionScaffolder.cs:line 105
   at TResult System.Linq.Enumerable+SelectListIterator<TSource, TResult>.TryGetFirst(out bool found)
   at TSource System.Linq.Enumerable.TryGetFirst<TSource>(IEnumerable<TSource> source, out bool found)
   at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
   at void RevEng.Core.Functions.SqlServerFunctionScaffolder.GenerateFunctionStub(Routine function, RoutineModel model) in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/Functions/SqlServerFunctionScaffolder.cs:line 115
   at string RevEng.Core.Functions.SqlServerFunctionScaffolder.WriteDbContext(ModuleScaffolderOptions scaffolderOptions, RoutineModel model) in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/Functions/SqlServerFunctionScaffolder.cs:line 69
   at ScaffoldedModel RevEng.Core.Modules.SqlServerRoutineScaffolder.ScaffoldModel(RoutineModel model, ModuleScaffolderOptions scaffolderOptions, ref List<string> errors) in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/Routines/SqlServerRoutineScaffolder.cs:line 221
   at SavedModelFiles RevEng.Core.ReverseEngineerScaffolder.GenerateFunctions(ReverseEngineerCommandOptions options, ref List<string> errors, string outputContextDir, string modelNamespace, string contextNamespace, bool supportsFunctions) in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/ReverseEngineerScaffolder.cs:line 157
   at ReverseEngineerResult RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/ReverseEngineerRunner.cs:line 112
   at async Task<int> EfReveng.Program.Main(string[] args) in C:/Code/Github/EFCorePowerTools/src/GUI/efreveng/Program.cs:line 69

   at ReverseEngineerResult EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(string output)
   at async Task<ReverseEngineerResult> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetOutputAsync()
   at async Task<ReverseEngineerResult> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.LaunchExternalRunnerAsync(ReverseEngineerOptions options, CodeGenerationMode codeGenerationMode, Project project)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GenerateFilesAsync(Project project, ReverseEngineerOptions options, string missingProviderPackage, bool onlyGenerate)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate, bool fromSqlProj)
```

My investigations:
when i executed the following sql query:
```
SELECT 
   SCHEMA_NAME(SCHEMA_ID) AS [Schema]
  ,SO.name AS [ObjectName]			   
  ,SO.Type_Desc AS [ObjectType (UDF/SP)]
  ,P.parameter_id AS [ParameterID]
  ,P.name AS [ParameterName]
  ,TYPE_NAME(P.user_type_id) AS [ParameterDataType]
  ,P.max_length AS [ParameterMaxBytes]
  ,P.is_output AS [IsOutPutParameter]
FROM sys.objects AS SO
INNER JOIN sys.parameters AS P ON SO.OBJECT_ID = P.OBJECT_ID
where parameter_id = 0
```

I get the following result:
|Schema|ObjectName|ObjectType (UDF/SP)|ParameterID|ParameterName|ParameterDataType|ParameterMaxBytes|IsOutPutParameter|
|---|---|---|---|---|---|---|---|
|dbo|allow_actual_value_fill|SQL_SCALAR_FUNCTION|0||bit|1|1|
|dbo|calcMetricPerformance|SQL_SCALAR_FUNCTION|0||decimal|9|1|
|dbo|calcMetricScore|SQL_SCALAR_FUNCTION|0||decimal|9|1|
|dbo|calcOverallPlannedScore|SQL_SCALAR_FUNCTION|0||decimal|9|1|
|dbo|calcScoreToDate|SQL_SCALAR_FUNCTION|0||decimal|9|1|
|dbo|fn_diagramobjects|SQL_SCALAR_FUNCTION|0||int|4|1|
|dbo|generateStrategicElementObjectId|SQL_SCALAR_FUNCTION|0||bigint|8|1|
|dbo|getErrorMessage|SQL_SCALAR_FUNCTION|0||nvarchar|2048|1|
|dbo|getKPIChartArea|SQL_SCALAR_FUNCTION|0||json|-1|1|
|dbo|getKPIChartData|SQL_SCALAR_FUNCTION|0||json|-1|1|
|dbo|getKpiStatus|SQL_SCALAR_FUNCTION|0||nvarchar|512|1|
|dbo|getLastDayOfMonth|SQL_SCALAR_FUNCTION|0||date|3|1|
|dbo|getObjectiveChartArea|SQL_SCALAR_FUNCTION|0||json|-1|1|
|dbo|getObjectiveChartData|SQL_SCALAR_FUNCTION|0||json|-1|1|
|dbo|getPerspectiveChartData|SQL_SCALAR_FUNCTION|0||json|-1|1|
|dbo|getPredicateCreator|SQL_SCALAR_FUNCTION|0||nvarchar|512|1|
|dbo|getThemeChartData|SQL_SCALAR_FUNCTION|0||json|-1|1|
|dbo|getThresholdColor|SQL_SCALAR_FUNCTION|0||nvarchar|512|1|
|dbo|is_department_decendant|SQL_SCALAR_FUNCTION|0||bit|1|1|
|dbo|is_obstacle_descendant|SQL_SCALAR_FUNCTION|0||bit|1|1|
|dbo|is_project_group_descendant|SQL_SCALAR_FUNCTION|0||bit|1|1|
|dbo|is_project_status_descendant|SQL_SCALAR_FUNCTION|0||bit|1|1|
|dbo|is_project_task_descendant|SQL_SCALAR_FUNCTION|0||bit|1|1|
|dbo|is_project_type_descendant|SQL_SCALAR_FUNCTION|0||bit|1|1|
|dbo|is_sector_decendant|SQL_SCALAR_FUNCTION|0||bit|1|1|
|dbo|resolveStrategicKpiDate|SQL_SCALAR_FUNCTION|0||date|3|1|

after checking the code  in `C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/Functions/SqlServerFunctionScaffolder.cs:line 105` i guess if you remove the `Code.Identifier` the problem will be ok  **I guess**

**Comment by ErikEJ** [comment]
@fshahin90 Yes, I will try the suggested fix. Expect an update later today.

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by fshahin90** [comment]
I guess the link is not updated yet from Microsoft side its still said last updated one day ago and the bulid number is 2.5.1290 but non the less i have tried it and still the same error appears
```
System.InvalidOperationException: Reverse engineer error: 
System.ArgumentException: The string argument 'name' cannot be empty.
   at string Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(string value, string parameterName)
   at string Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Identifier(string name, ICollection<string> scope, bool? capitalize)
   at void RevEng.Core.Functions.SqlServerFunctionScaffolder.GenerateFunctionStub(Routine function, RoutineModel model)+(ModuleParameter p) => { } in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/Functions/SqlServerFunctionScaffolder.cs:line 105
   at TResult System.Linq.Enumerable+SelectListIterator<TSource, TResult>.TryGetFirst(out bool found)
   at TSource System.Linq.Enumerable.TryGetFirst<TSource>(IEnumerable<TSource> source, out bool found)
   at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
   at void RevEng.Core.Functions.SqlServerFunctionScaffolder.GenerateFunctionStub(Routine function, RoutineModel model) in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/Functions/SqlServerFunctionScaffolder.cs:line 115
   at string RevEng.Core.Functions.SqlServerFunctionScaffolder.WriteDbContext(ModuleScaffolderOptions scaffolderOptions, RoutineModel model) in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/Functions/SqlServerFunctionScaffolder.cs:line 69
   at ScaffoldedModel RevEng.Core.Modules.SqlServerRoutineScaffolder.ScaffoldModel(RoutineModel model, ModuleScaffolderOptions scaffolderOptions, ref List<string> errors) in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/Routines/SqlServerRoutineScaffolder.cs:line 221
   at SavedModelFiles RevEng.Core.ReverseEngineerScaffolder.GenerateFunctions(ReverseEngineerCommandOptions options, ref List<string> errors, string outputContextDir, string modelNamespace, string contextNamespace, bool supportsFunctions) in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/ReverseEngineerScaffolder.cs:line 157
   at ReverseEngineerResult RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:/Code/Github/EFCorePowerTools/src/GUI/RevEng.Core/ReverseEngineerRunner.cs:line 112
   at async Task<int> EfReveng.Program.Main(string[] args) in C:/Code/Github/EFCorePowerTools/src/GUI/efreveng/Program.cs:line 69

   at ReverseEngineerResult EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(string output)
   at async Task<ReverseEngineerResult> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.GetOutputAsync()
   at async Task<ReverseEngineerResult> EFCorePowerTools.Handlers.ReverseEngineer.EfRevEngLauncher.LaunchExternalRunnerAsync(ReverseEngineerOptions options, CodeGenerationMode codeGenerationMode, Project project)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.GenerateFilesAsync(Project project, ReverseEngineerOptions options, string missingProviderPackage, bool onlyGenerate)
   at async Task EFCorePowerTools.Handlers.ReverseEngineer.ReverseEngineerHandler.ReverseEngineerCodeFirstAsync(Project project, string optionsPath, bool onlyGenerate, bool fromSqlProj)

```

**Comment by ErikEJ** [comment]
@fshahin90 You need a build from Vsixgallery, it has just been published!

**Comment by ErikEJ** [comment]
Build 1293 or later

**Comment by fshahin90** [comment]
yes, just got updated and I just tested it and it worked.
Many thanks for your help.
May i suggest that if you can use the GitHub releases for the project to keep couple old release so any one can revert back to older version if anything happened after an update!!!

**Comment by ErikEJ** [comment]
@fshahin90 Thanks for the suggestion, but I currently does not use GitHub for building, I use AppVeyor, and have older builds available there. But prefer to just move forward rather than supporting older builds.

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
