### ISSUE TITLE
"Not Supported"

### ISSUE THREAD

**Issue by notBlubbll** [ErikEJ/EFCorePowerTools#1988]
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/149101422/47df8617-d193-48c1-9318-a83eac5e06f4)

when creating a new model from the contextmenu this appears. latest vs 2022, latest ef core + packages + vs addon

**Comment by ErikEJ** [comment]
Are you targeting .net 6 or newer? 

Pls share your .csproj contents.

**Comment by notBlubbll** [comment]
> Are you targeting .net 6 or newer?
> 
> Pls share your .csproj contents.

`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <SelfContained>false</SelfContained>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <StaticWebAssetsEnabled>False</StaticWebAssetsEnabled>
    <Configurations>Debug;Release;Development;Staging;Production</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="MVVM\Components\Component.razor" />
    <Content Remove="MVVM\Components\DebugConsole.razor" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EfCore.SchemaCompare" Version="7.0.0" />
    <PackageReference Include="BlazorDownloadFile" Version="2.4.0.2" />
    <PackageReference Include="ClosedXML" Version="0.104.0-preview2" />
    <PackageReference Include="CurrieTechnologies.Razor.SweetAlert2" Version="5.5.0" />
    <PackageReference Include="LdapForNet" Version="2.7.15" />
    <PackageReference Include="Microsoft.Graph" Version="5.31.0" />
    <PackageReference Include="Microsoft.Graph.Core" Version="3.0.11" />
    <PackageReference Include="Microsoft.Identity.Web" Version="2.15.3" />
    <PackageReference Include="Microsoft.Web.Administration" Version="11.1.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="6.1.0" />
    <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="8.0.0-rc.2.23480.1-02" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.0-rc.2.23480.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.0-rc.2.23480.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.0-rc.2.23480.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0-rc.2.23480.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0-rc.2.23480.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.DirectoryServices" Version="8.0.0-rc.2.23479.6" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="8.0.0-rc.2.23479.6" />
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0-rc.2.23479.6" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="MVVM\Resources\locale\value.Designer.cs">
      <DependentUpon>value.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Resources.Designer.cs">
      <DependentUpon>Resources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="MVVM\Resources\locale\value.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\Resources\locale\value.resx">
      <SubType>Designer</SubType>
      <LastGenOutput>value.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Resources.resx">
      <SubType>Designer</SubType>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="MVVM\Components\Component.razor" />
    <None Include="MVVM\Components\DebugConsole.razor" />
  </ItemGroup>
  <ItemGroup>
    <UpToDateCheckInput Remove="MVVM\Components\Component.razor" />
  </ItemGroup>
  <ItemGroup>
    <_ContentIncludedByDefault Remove="MVVM\Components\Component.razor" />
  </ItemGroup>
</Project>`

**Comment by ErikEJ** [comment]
Are you running VS 17.8 (as stated in the error message and asked when you created this issue!)

**Comment by notBlubbll** [comment]
> Are you running VS 17.8 (as stated in the error message and asked when you created this issue!)

nope

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/149101422/d4640a4c-b70f-4622-8580-5bdab4e9d678)

**Comment by notBlubbll** [comment]
oh nevermind then, time to upgrade i guess, i somehow thought it meant vs 2017

**Comment by ErikEJ** [comment]
I will update the text. But you need 17.8 preview to build a .net 8 project.

**Comment by notBlubbll** [comment]
> I will update the text. But you need 17.8 preview to build a .net 8 project.

i enabled preview features, that's why i am able to use net 8 in that version already.
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/149101422/27fdc60e-5e92-4352-ad37-1985ee6fa5e5)
but yeah for the power tools addon (at least for the models for now) i'll be switching to the 2022 preview installation

**Comment by ErikEJ** [comment]
Ah! I did not know of this - maybe the check is to strict. I will amend

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by notBlubbll** [comment]
Nope, i sadly still get the warning.
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/149101422/92843874-1fe2-4840-a73f-d17fb3426616)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/149101422/365685b5-9a06-41d5-9e44-3081fdb06d04)
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/149101422/1e81149b-747d-450a-80e6-ba0fd3e09b3c)

**Comment by notBlubbll** [comment]
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/149101422/e6b91e45-ffc5-4430-adeb-3f0ea27a5cf2)
sorry, last tests were done during an vs upgrade and somehow the .net 8 references messed up too, my whole vs was borked.
it works now, thanks for your work!
