### ISSUE TITLE
EF Core Power Tools and .NET 8

### ISSUE THREAD

**Issue by CliffConway** [ErikEJ/EFCorePowerTools#2016]
I have created a simple class library and attempted to use the EF Core Power Tools which generates a Method Exception.

Environment:-
- .NET 8 x64 Intel
- EF Core Power Toos - 2.5.1678
- Visual Studio - Version 17.8.0
- Database - MySQL
- EF Core 8

Package references:-
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.0-beta.2" />

STeps to produce
- create a C# class library
- access EF Core Power Tools
- select <Reverse Engineer>
- select Database connection to MySQL database
- select all defaults in the ensuing dialogues
- error message 👎 
Some issues were discovered during reverse engineering, consider addressing them:

System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.Clone(Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingInfo ByRef)'.
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlTypeMappingSource.FindMapping(RelationalTypeMappingInfo& mappingInfo)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.<>c.<FindMappingWithConversion>b__8_0(ValueTuple`4 k, RelationalTypeMappingSource self)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo mappingInfo, Type providerClrType, ValueConverter customConverter)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo mappingInfo, IReadOnlyList`1 principals)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(String storeTypeName)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ScaffoldingTypeMapper.FindMapping(String storeType, Boolean keyOrIndex, Boolean rowVersion, Type clrType)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.GetTypeScaffoldingInfo(DatabaseColumn column)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitColumn(EntityTypeBuilder builder, DatabaseColumn column)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitColumns(EntityTypeBuilder builder, ICollection`1 columns)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at RevEng.Core.ColumnRemovingScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core.60\ColumnRemovingScaffoldingModelFactory.cs:line 87
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, Boolean dbContextOnly, Boolean entitiesOnly, Boolean useSchemaFolders, Boolean useSchemaNamespaces) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 487
   at RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List`1 schemas, String outputContextDir, String modelNamespace, String contextNamespace, String projectPath, String outputPath) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 94
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:\Code\Github\EFCorePowerTools\src\GUI\RevEng.Core.60\ReverseEngineerRunner.cs:line 86

See attached zip file with the small project 

[PrestaShopLibrary.zip](https://github.com/ErikEJ/EFCorePowerTools/files/13434751/PrestaShopLibrary.zip)

**Comment by CliffConway** [comment]
Not sure why my Packages references are not showing (at least in my view of the submitted task) so I have included them again without surrounding XML chevrons in the event they are causing the problem

  PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.0"
  PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0"
  PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0"
  PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0"
  PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.0-beta.2"

**Comment by ErikEJ** [comment]
Have you tried the latest daily build? 

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by CliffConway** [comment]
Thanks Erik for the very fast response. I'll give that a go.

However, I just noticed a recent comment (3 hours ago) on the Pomelo forum that indicates this Method Exception is still occurring for that user also. (ref:- https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1746 )

Many thanks again and a big thumbs up to your wonderful tool :-))

**Comment by CliffConway** [comment]
Erik that did the trick. I got a few minor warnings but the model was built successfully

Many thanks again

Cliff

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by CliffConway** [comment]
Will do both
