### ISSUE TITLE
Auto generated configuration classes not formatted properly

### ISSUE THREAD

**Issue by fmir864** [ErikEJ/EFCorePowerTools#2125]
### Provide steps to reproduce a bug

1. Create an ASP Core Razor pages application using .NET 8.0
2. Restore [AdventureWorksLT2019.bak](https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorksLT2019.bak)
3. Reverse engineer using EF Core Power tools. Keep all default, only select "**Split DbContext into Configuration classes**" option
4. Click Ok
5. The generated config classes not formatted properly

Sample: [AdventureWorks.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14071688/AdventureWorks.zip)

### Provide technical details

- EF Core Power Tools version: 2.6.72

- Exact Visual Studio version: Visual Studio 2022 17.8.5

- Database engine: SQL Server 2019

- EF Core version in use: EF Core 8

- Is Handlebars templates used: no

- Is T4 templates used: no

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by fmir864** [comment]
Thanks @ErikEJ, I downloaded the latest daily build `v2.6.95`, but unfortunately the issue still persists. I have attached the sample again with a repeating the reverse engineering.

[AdventureWorks.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14079478/AdventureWorks.zip)

**Comment by ErikEJ** [comment]
@fmir864 There were some build issues, you need build 2.6.97 or later

**Comment by ErikEJ** [comment]
@fmir864 Ping?

**Comment by fmir864** [comment]
Sorry for late Pong @ErikEJ, I tried with `2.6.97` but unfortunately the issue still persists. Please find the attached.

[AdventureWorks.zip](https://github.com/ErikEJ/EFCorePowerTools/files/14095124/AdventureWorks.zip)

**Comment by ErikEJ** [comment]
I am unable to repro
