### ISSUE TITLE
[Bug] CLI column removal check is too restricitive

### ISSUE THREAD

**Issue by MauroVevy** [ErikEJ/EFCorePowerTools#2377]
# Feature proposal

I need to create a copy of some tables and columns from our ERP database to a little local database.

I have found these behaviors to limit the creation of models and context.

* When I choose columns to include in my models from interactive mode, all columns that have a foreign key with another table have the checkbox disabled.
This is strange because in my case I don't include the reference table in my local database.

* The configuration file `efpt.config.json` has an `excludeColums` section for each table.
It could also be useful to have a choice between `excludeColumns`  or `includeColumns` to use when the columns to create the model are very few in number compared to the total.

* Add the `Split DbContext into Configuration classed` option also for `efcpt` version

**Comment by ErikEJ** [comment]
>> This column has a foreign key for a table that is not present in my new database.

Maybe this warning is triggered too early?

**Comment by ErikEJ** [comment]
I get what you are asking for and it makes sense...

**Comment by MauroVevy** [comment]
Another features

1. Does the cli tool manage the renaming of tables and columns?
2. Would it be possible to add an optional parameter to decide which configuration file to take?
It would be nice
efptc "connectionstring" mssql local
the tools use or create this config files
efptc-local-config.json
efptc-local-renaming.json



Thanks a lot again

**Comment by ErikEJ** [comment]
re 1: Yes, same format file as the GUI tool

re 2: There is the -i parameter:

-i, --input            Full pathname to the efcpt-config.json file, default is
                         'efcpt-config.json' in currrent directory

**Comment by MauroVevy** [comment]
@ErikEJ 
Do you plan to implement the requested functionality?
If not, is there a workaround?

Another question.
What's the naming convention  of renaming file  ?

For Example:
The gui version use 
`efpt.config.json` and `efpt.Chinook.config.json` and I suppose `efpt.Chinook.renaming.json`.
It's correct ?

for command cli ?
I tried
`efcpt-Local.config` and `efcpt-Local-renaming.config` calling `efcpt` with `-i` parameter.
but the renaming file is not taken into account

**Comment by ErikEJ** [comment]
@MauroVevy 

> Do you plan to implement the requested functionality?

Do you plan to pay me for it? 😄 

Joke aside, maybe sometime, but exactly what is "the requested functionalty" ??- there is a lot (too much) going on in this issue.

> What's the naming convention of renaming file ?

As [well documented](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-efptrenamingjson) the name is `efpt.renaming.json`

**Comment by MauroVevy** [comment]
You're absolutely right, sorry.

## Feature requested:
Permit, with a parameter in the `efcpt.config.json` or in other way, to avoid the following message and generate model without columns with foreignkey o primarykey in the source database.
Now I receive this message:
`warning: [dbo].[myTable].myColumn cannot be excluded because it is either a Primary Key or Foreign Key of another Mapped Column.  This entry has been removed from the config file.`


About the renaming.

I created a configuration file for cli version of EFCore power tools named: `efcpt-localdb-config.json`.
Note: The file name contains `localdb`.

I run this command: `efcpt "connectionString" mssql -i efcpt-localdb-config.json`
What's the corresponding name of  `renaming file` for this run ?

**Comment by ErikEJ** [comment]
efpt.renaming.json as I wrote above..

**Comment by ErikEJ** [comment]
Please share a simple repro and I might have a look at your feature request (sounds more like a bug...)

**Comment by MauroVevy** [comment]
So I can have multiple configuration files and only 1 renaming file in the same folder?

I try to prepare a repro.

**Comment by ErikEJ** [comment]
> So I can have multiple configuration files and only 1 renaming file in the same folder?

Currently, but you can have many config files in multiple folders with each their own renaming file.

**Comment by MauroVevy** [comment]
# Repro

Create a database called `EfcptTest` with this tables

* `Customers`
* `SaleOrders`
* `SaleOrderRows`

From this database I wont use only `SaleOrders` and `SaleOrderRow` tables.
**Remove from `SaleOrders` the column `Customer`** because in my database I don't need of customers.

When I run `efcpt` the `Customer` column isn't removed.

Here are all the steps to reproduce the problem

## Db Creation

```sql
create database EfcptTest
```

## Create Customer table

```sql
CREATE TABLE [dbo].[Customers](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Surname] [nvarchar](50) NULL,
	[Address] [nvarchar](50) NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

```

## Create Sale Orders Table

```sql
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SaleOrders](
	[Id] [int] NOT NULL,
	[OrderNo] [nvarchar](50) NULL,
	[Customer] [int] NULL,
	[Date] [date] NULL,
 CONSTRAINT [PK_SaleOrders] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SaleOrders]  WITH CHECK ADD  CONSTRAINT [FK_SaleOrders_Customers] FOREIGN KEY([Customer])
REFERENCES [dbo].[Customers] ([Id])
GO

ALTER TABLE [dbo].[SaleOrders] CHECK CONSTRAINT [FK_SaleOrders_Customers]
GO
```

## Create Sale Order Rows

```sql
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SaleOrderRows](
	[Id] [int] NOT NULL,
	[Row] [int] NULL,
	[Code] [nvarchar](50) NULL,
	[Description] [nvarchar](50) NULL,
	[Price] [numeric](18, 0) NULL,
 CONSTRAINT [PK_SaleOrderRows] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SaleOrderRows]  WITH CHECK ADD  CONSTRAINT [FK_SaleOrderRows_SaleOrders] FOREIGN KEY([Id])
REFERENCES [dbo].[SaleOrders] ([Id])
GO

ALTER TABLE [dbo].[SaleOrderRows] CHECK CONSTRAINT [FK_SaleOrderRows_SaleOrders]
GO

```

## Efpct Configuration files

```json
{
  "$schema": "https://raw.githubusercontent.com/ErikEJ/EFCorePowerTools/master/samples/efcpt-schema.json",
  "code-generation": {
    "enable-on-configuring": false,
    "generate-mermaid-diagram": false,
    "merge-dacpacs": false,
    "refresh-object-lists": false,
    "remove-defaultsql-from-bool-properties": false,
    "soft-delete-obsolete-files": true,
    "t4-template-path": null,
    "type": "all",
    "use-alternate-stored-procedure-resultset-discovery": false,
    "use-data-annotations": false,
    "use-database-names": false,
    "use-decimal-data-annotation-for-sproc-results": true,
    "use-inflector": true,
    "use-legacy-inflector": false,
    "use-many-to-many-entity": false,
    "use-nullable-reference-types": true,
    "use-prefix-navigation-naming": false,
    "use-t4": false
  },
  "file-layout": {
    "output-dbcontext-path": null,
    "output-path": "Models",
    "split-dbcontext-preview": true
  },
  "functions": [
    {
      "exclusionWildcard": "*"
    }
  ],
  "names": {
    "dbcontext-name": "EfcptContext",
    "dbcontext-namespace": null,
    "model-namespace": null,
    "root-namespace": "EfpctTest"
  },
  "stored-procedures": [
    {
      "exclusionWildcard": "*"
    }
  ],
  "tables": [
    {
      "exclusionWildcard": "*"
    },
    {
      "name": "[dbo].[SaleOrders]",
      "exclude": false,
      "excludedColumns": [
        "Customer"
      ]
    },
    {
      "name": "[dbo].[SaleOrderRows]",
      "exclude": false,
      "excludedColumns": [
      ]
    }
  ],
  "views": [
    {
      "exclusionWildcard": "*"
    }
  ]
}
```

<center>efcpt-config.json</center>

```
[
  {
    "SchemaName": "dbo",
    "Tables": [
      {
        "Columns": [
          {
            "Name": "Id",
            "NewName": "IdOrder"
          }
        ],
        "Name": "SaleOrders",
        "NewName": "SaleOrders"
      },
      {
        "Columns": [
          {
            "Name": "Code",
            "NewName": "ItemCode"
          },
          {
            "Name": "Price",
            "NewName": "UnitPrice"
          }
        ],
        "Name": "SaleOrderRows",
        "NewName": "SaleOrderRows"
      }
    ],
    "UseSchemaName": false
  }
]
```

<center>efpt.renaming.json</center>

## Command

```bash
efcpt "Server=[myServer]; Database=EFCPTTTest; Trusted_Connection=Yes; Integrated Security=true; TrustServerCertificate=true;" mssql 
```

Change `[myServer]` with yours.

## Warning

This is the message received after the command

```
warning: [dbo].[SaleOrders].Customer cannot be excluded because it is either a Primary Key or Foreign Key of another
Mapped Column.  This entry has been removed from the config file.
```

The Customer column is present in models

**Comment by ErikEJ** [comment]
I implemented a fix for this in the latest CLI nightly

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by MauroVevy** [comment]
I tried the new night version and one warning disappeared.
But, I still have this message:
```
error: System.InvalidOperationException: The property 'MbmgMbscId' cannot be added to the type 'Warehouse
(Dictionary<string, object>)' because no property type was specified and there is no corresponding CLR property or
field. To add a shadow state property, the property type must be specified.
```
The model and database context of the corresponding table are not created.

The property 'MbmgMbscId' is a removed column.
If I try with the above example `efcpt` works.
Can you help me understand the source of the problem?
Thanks


Another question.
Is there a way to choose the class name of the generated entity?
Now, if my table is called "My_Table", I will have a class called "MyTable".
For example, what if I wanted efcpt to generate a class called "MyLocalTable"?

**Comment by ErikEJ** [comment]
You most likely now have an invalid model, and this is causing the runtime error (as I mentioned in my first reply!).

For the other question, please create a new issue.

**Comment by MauroVevy** [comment]
Ok, I'll create a new issue.

In any case
I have a correct model, the problem is the presence of the removed column in an index.

**Comment by ErikEJ** [comment]
Yeah, that is why the GUI restricts the columns you can remove...
