### ISSUE TITLE
Remove a column present in a unique constraint

### ISSUE THREAD

**Issue by MauroVevy** [ErikEJ/EFCorePowerTools#2388]
# Scenario
_I have to create a series of databases with a limited number of tables and columns compared to the original one, kept in reading synchronization with the original database via a service, on which to run as many small procedures.
This allows me to have specific functions or views without modifying the original database._

# Problem

***If in the efpct configuration file I exclude a column that is part of an index, I get the following error***

```
error: System.InvalidOperationException: The property 'ColumnName' cannot be added to the type 'TableName
(Dictionary<string, object>)' because no property type was specified and there is no corresponding CLR property or
field. To add a shadow state property, the property type must be specified.
```

# Request

Allow you to remove any column and recreate any index that contained it with the remaining columns

# Repro

Create a database called `EfcptTest` with this tables

* `Customers`
* `SaleOrders`
* `SaleOrderRows`

From this database I wont use only `SaleOrders` and `SaleOrderRow` tables.
**Remove from `SaleOrders` the column `Customer`** because in my database I don't need of customers.

Here are all the steps to reproduce the problem

## Db Creation

```sql
create database EfcptTest
GO

use EfcptTest
GO
```

## Create Customer table

```sql
CREATE TABLE [dbo].[Customers](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Surname] [nvarchar](50) NULL,
	[Address] [nvarchar](50) NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

```

## Create Sale Orders Table

```sql
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SaleOrders](
	[Id] [int] NOT NULL,
	[OrderNo] [nvarchar](50) NULL,
	[Customer] [int] NULL,
	[Date] [date] NULL,
 CONSTRAINT [PK_SaleOrders] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_SaleOrders] UNIQUE NONCLUSTERED 
(
	[Id] ASC,
	[OrderNo] ASC,
	[Customer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
```

## Note

**In table `SaleOrders` `Customer` is part of an index**

## Create Sale Order Rows

```sql
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SaleOrderRows](
	[Id] [int] NOT NULL,
	[Row] [int] NULL,
	[Code] [nvarchar](50) NULL,
	[Description] [nvarchar](50) NULL,
	[Price] [numeric](18, 0) NULL,
 CONSTRAINT [PK_SaleOrderRows] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SaleOrderRows]  WITH CHECK ADD  CONSTRAINT [FK_SaleOrderRows_SaleOrders] FOREIGN KEY([Id])
REFERENCES [dbo].[SaleOrders] ([Id])
GO

ALTER TABLE [dbo].[SaleOrderRows] CHECK CONSTRAINT [FK_SaleOrderRows_SaleOrders]
GO

```

## Efpct Configuration files

```json
{
  "$schema": "https://raw.githubusercontent.com/ErikEJ/EFCorePowerTools/master/samples/efcpt-schema.json",
  "code-generation": {
    "enable-on-configuring": false,
    "generate-mermaid-diagram": false,
    "merge-dacpacs": false,
    "refresh-object-lists": false,
    "remove-defaultsql-from-bool-properties": false,
    "soft-delete-obsolete-files": true,
    "t4-template-path": null,
    "type": "all",
    "use-alternate-stored-procedure-resultset-discovery": false,
    "use-data-annotations": false,
    "use-database-names": false,
    "use-decimal-data-annotation-for-sproc-results": true,
    "use-inflector": true,
    "use-legacy-inflector": false,
    "use-many-to-many-entity": false,
    "use-nullable-reference-types": true,
    "use-prefix-navigation-naming": false,
    "use-t4": false
  },
  "file-layout": {
    "output-dbcontext-path": null,
    "output-path": "Models",
    "split-dbcontext-preview": true
  },
  "functions": [
    {
      "exclusionWildcard": "*"
    }
  ],
  "names": {
    "dbcontext-name": "EfcptContext",
    "dbcontext-namespace": null,
    "model-namespace": null,
    "root-namespace": "EfpctTest"
  },
  "stored-procedures": [
    {
      "exclusionWildcard": "*"
    }
  ],
  "tables": [
    {
      "exclusionWildcard": "*"
    },
    {
      "name": "[dbo].[SaleOrders]",
      "exclude": false,
      "excludedColumns": [
        "Customer"
      ]
    },
    {
      "name": "[dbo].[SaleOrderRows]",
      "exclude": false,
      "excludedColumns": [
      ]
    }
  ],
  "views": [
    {
      "exclusionWildcard": "*"
    }
  ]
}
```

<center>efcpt-config.json</center>

## Command

```bash
efcpt "Server=[myServer]; Database=EFCPTTTest; Trusted_Connection=Yes; Integrated Security=true; TrustServerCertificate=true;" mssql 
```

Change `[myServer]` with yours.

## Error

This is the message received after the command

```
error: System.InvalidOperationException: The property 'Customer' cannot be added to the type 'SaleOrder
(Dictionary<string, object>)' because no property type was specified and there is no corresponding CLR property or
field. To add a shadow state property, the property type must be specified.
```

**Comment by ErikEJ** [comment]
@MauroVevy  Thanks for reporting this, seems like a bug as I already have some code attempting to remove indexes affected by column removal

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by MauroVevy** [comment]
In this example your change works, but in our CRM database I still get the error.
I'm trying to figure out what other constraints there are between the columns.

Thanks for all

**Comment by MauroVevy** [comment]
With the example above, I always get the same error.

```

error: System.InvalidOperationException: The property 'Customer' cannot be added to the type 'SaleOrder (Dictionary<string, object>)' because no property type was specified   
and there is no corresponding CLR property or field. To add a shadow state property, the property type must be specified.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalTypeBaseBuilder.Property(Type propertyType, String propertyName, MemberInfo memberInfo, Nullable`1
typeConfigurationSource, Nullable`1 configurationSource, Boolean skipTypeCheck)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalTypeBaseBuilder.Property(Type propertyType, String propertyName, Nullable`1 typeConfigurationSource, Nullable`1  
configurationSource, Boolean skipTypeCheck)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalTypeBaseBuilder.GetOrCreateProperties(IReadOnlyList`1 propertyNames, Nullable`1 configurationSource,
IReadOnlyList`1 referencedProperties, Boolean required, Boolean useDefaultType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasIndex(IReadOnlyList`1 propertyNames, String name, ConfigurationSource configurationSource)  
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.HasIndex(String[] propertyNames, String name)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitUniqueConstraint(EntityTypeBuilder builder, DatabaseUniqueConstraint
uniqueConstraint)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitUniqueConstraints(EntityTypeBuilder builder, ICollection`1 uniqueConstraints)  
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at RevEng.Core.ColumnRemovingScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table) in
D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ColumnRemovingScaffoldingModelFactory.cs:line 87
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions,      
ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, Boolean dbContextOnly, Boolean entitiesOnly, Boolean useSchemaFolders, 
Boolean useSchemaNamespaces) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 488
   at RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List`1 schemas, String outputContextDir, String modelNamespace, String    
contextNamespace, String projectPath, String outputPath) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 94
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in
D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerRunner.cs:line 86
```

**Comment by MauroVevy** [comment]
efcpt --version                                                                                                                     
efcpt.8 8.1.260-nightly+c2fcc2735f13f87ad5d9b2ccfe33568f100eea6d

**Comment by MauroVevy** [comment]
Retried with                                                                                                              
efcpt.8 8.1.262-nightly+b8d5999971623ad7d8d548c399e5de4584e6f76a

And this example works

**Comment by ErikEJ** [comment]
It is old! Latest is .262

**Comment by ErikEJ** [comment]
@MauroVevy Looking forward to a status when running against your actual CRM db

**Comment by MauroVevy** [comment]
I found another case when there is a foreign key between a column and a key of the same table.
Do I have to open another issue?

**Comment by ErikEJ** [comment]
@MauroVevy yes
