### ISSUE TITLE
T4 Template Local Assembly Path Suddenly Broken?

### ISSUE THREAD

**Issue by sunnylarr** [ErikEJ/EFCorePowerTools#2467]
Hello, my team has been using EF Power Tools for a few months now with no major issues, but just recently we have noticed a bug when trying to run EF Power Tools reverse engineering on our efpt config json files using custom T4 template files.

This is the current error we're running into:

```
error CS0006: Metadata file 'MyProject\Libs\PluralizeService.Core.dll' could not be found

Microsoft.EntityFrameworkCore.Design.OperationException: Processing 'C:\Users\LSun123\Repos\Common\MyProject\.\CodeTemplates\EFCore\DbContext.t4' failed.
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.TextTemplatingModelGenerator.HandleErrors(TextTemplatingEngineHost host)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.TextTemplatingModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
   at RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, Boolean dbContextOnly, Boolean entitiesOnly, Boolean useSchemaFolders, Boolean useSchemaNamespaces) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 490
   at RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List`1 schemas, String outputContextDir, String modelNamespace, String contextNamespace, String projectPath, String outputPath) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerScaffolder.cs:line 94
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in C:\Code\Github\EFCorePowerTools\src\Core\RevEng.Core.60\ReverseEngineerRunner.cs:line 78
```

In our `DbContext.t4` template file, the assembly and import section looked something like this:
```dotnet
<#@ template hostSpecific="true" #>
<#@ assembly name="Microsoft.EntityFrameworkCore" #>
<#@ assembly name="Microsoft.EntityFrameworkCore.Design" #>
<#@ assembly name="Microsoft.EntityFrameworkCore.Relational" #>
<#@ assembly name="Microsoft.Extensions.DependencyInjection.Abstractions" #>
<#@ assembly name="MyProject\Libs\PluralizeService.Core.dll" #>
<#@ parameter name="Model" type="Microsoft.EntityFrameworkCore.Metadata.IModel" #>
<#@ parameter name="Options" type="Microsoft.EntityFrameworkCore.Scaffolding.ModelCodeGenerationOptions" #>
<#@ parameter name="NamespaceHint" type="System.String" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Text" #>
<#@ import namespace="System.IO" #>
<#@ import namespace="Microsoft.EntityFrameworkCore" #>
<#@ import namespace="Microsoft.EntityFrameworkCore.Design" #>
<#@ import namespace="Microsoft.EntityFrameworkCore.Infrastructure" #>
<#@ import namespace="Microsoft.EntityFrameworkCore.Scaffolding" #>
<#@ import namespace="Microsoft.Extensions.DependencyInjection" #>
<#@ import namespace="PluralizeService.Core" #>
```

And the `MyProject\Libs\PluralizeService.Core.dll` assembly path worked previously. But now, it is not recognizing that path anymore.

Looking into it further, when I used an absolute path, such as `C:\Users\LSun123\Repos\Common\MyProject\Libs\PluralizeService.Core.dll` it did work.

When I tried to print out the working directory in the generated context file, I noticed it was pointing to `C:\Windows\system32\`:
```dotnet
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using MyProject.Models.Test;

namespace MyProject.Data.Test;
/// <summary>
/// Working Directory: C:\Windows\system32
/// </summary> 
public partial class TestContext : DbContext
{
...
```

Why did the working directory change from the project's directory to the windows system32 directory? Is there a way to change the working directory? What update changed how the template files are being processed?

Any help in this matter would be greatly appreciated. Thanks!

### Provide steps to reproduce a bug

Please include a **complete** description of the issue or link to a project that I can run to reproduce the issue.

### Provide technical details

- EF Core Power Tools version: 2.6.420

- Exact Visual Studio version: Visual Studio Pro 2022 17.10.0

- Database engine: SQL Server

- EF Core version in use: EF Core 7

- Is Handlebars templates used: no

- Is T4 templates used: yes

- Is a SQL Server .dacpac used: no

**Comment by ErikEJ** [comment]
Maybe an update of the EF Core T4 Dependency?? Have you tried EF Core 8 (7 is no longer supported)

**Comment by ErikEJ** [comment]
Maybe remove the .dll part from the path?

**Comment by sunnylarr** [comment]
Removing the .dll part did not work, we have the dll stored at that exact location (MyProject\Libs\PluralizeService.Core.dll).
I upgraded to my project to .NET 8 and upgraded to EF Core 8 and also ran `dotnet new update` to update all my template files to the latest. 
I still get the same error.

This is the epft config file if there are any clues:
```json
{
   "CodeGenerationMode": 4,
   "ContextClassName": "TestContext",
   "ContextNamespace": "",
   "FilterSchemas": false,
   "IncludeConnectionString": false,
   "ModelNamespace": "Models.Test",
   "OutputContextPath": "Data\\Test",
   "OutputPath": "Models\\Test",
   "PreserveCasingWithRegex": true,
   "ProjectRootNamespace": "MyProject",
   "Schemas": null,
   "SelectedHandlebarsLanguage": 2,
   "SelectedToBeGenerated": 0,
   "T4TemplatePath": ".",
   "Tables": [
      {
         "Name": "[my_db].[MyTestTable]",
         "ObjectType": 0
      }
   ],
   "UiHint": null,
   "UncountableWords": null,
   "UseAsyncStoredProcedureCalls": true,
   "UseBoolPropertiesWithoutDefaultSql": false,
   "UseDatabaseNames": false,
   "UseDateOnlyTimeOnly": false,
   "UseDbContextSplitting": false,
   "UseDecimalDataAnnotationForSprocResult": true,
   "UseFluentApiOnly": true,
   "UseHandleBars": false,
   "UseHierarchyId": false,
   "UseInflector": false,
   "UseLegacyPluralizer": false,
   "UseManyToManyEntity": false,
   "UseNoDefaultConstructor": false,
   "UseNoNavigations": false,
   "UseNoObjectFilter": false,
   "UseNodaTime": false,
   "UseNullableReferences": false,
   "UsePrefixNavigationNaming": false,
   "UseSchemaFolders": false,
   "UseSchemaNamespaces": false,
   "UseSpatial": false,
   "UseT4": true
}
```

**Comment by ErikEJ** [comment]
The template processing is independent of the Power Tools pipeline,  I think you will see the same issue with the built in tooling.

**Comment by sunnylarr** [comment]
Ah ok, that makes sense. I also noticed that when I try to print out project properties such as: `<#= this.Host.ResolveAssemblyReference("$(SolutionDir)") #>` it would hang the entire generation process and I would need to close Visual Studio to stop it.

Does that mean there is a problem with the `hostspecific` option in the first template line? `<#@ template hostSpecific="True" language="C#" #>`

**Comment by sunnylarr** [comment]
I also tried to use project macros such as `$(SolutionDir)` to add the assembly like so: 
`<#@ assembly name="$(SolutionDir)\MyProject\Libs\PluralizeService.Core.dll" #>`

But I still get the same error:
```
error CS0006: Metadata file '$(SolutionDir)\MyProject\Libs\PluralizeService.Core.dll' could not be found
```

**Comment by ErikEJ** [comment]
I would take  step back and then repro with the standard EF Core CLI. If you can repro, report in the EF Core repro

**Comment by sunnylarr** [comment]
I've installed EF Core Power Tools CLI, created a new efcpt-config.json file and modified it to use t4 templates.

After correctly setting up the CLI command and running it, I still get the same error as before regarding the local assembly file (PluralizeService.Core.dll) not being found.

**Comment by ErikEJ** [comment]
I meant try the standard EF Core CLI, not Power Tools.

**Comment by sunnylarr** [comment]
Ah ok, sorry for misreading. 

I did try to run `dotnet ef dbcontext scaffold ...` to purely test the templates and the same error happens, so it looks like an issue with EF Core. I'll create an issue with them. Thank you.

**Comment by ErikEJ** [comment]
Looks like this could be fixed for WF Core 8 by referencing a newer version of Mono.TextTemplating

**Comment by sunnylarr** [comment]
Hi Eric, sorry for the late response but I haven't been able to work on this issue due to other priorities. Is there a roadmap for when EF Power Tools would have EF Core 8 support? I'm thinking that even if the fix works with pure EF Core, we still wouldn't be able to use the EF Power Tools until the dependency is updated too.

**Comment by ErikEJ** [comment]
@sunnylarr Are you asking for when I have free time to fix this for you?

Do you sponsor me? If so, that may improve the chances for a quicker fix. I also accept pull requests.

**Comment by sunnylarr** [comment]
Not at all, just wondering if or when EF Power Tools will have support for EF Core 8. 
I'm just gauging if we can keep using our current workaround until an upgraded version is released, or if we should pursue creating a pull request instead.

**Comment by ErikEJ** [comment]
I plan to update the EF Core 8 tools with the Mono.TextTempkating 3.0.0 within the next week

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by sunnylarr** [comment]
Unfortunately the latest build did not fix the issue. I'm starting to believe it is not an issue with the tools but with a recent update with Visual Studio that is causing the issue. As I've said, the issue appeared out of nowhere and the only thing that could have changed would be Visual Studio.

We will keep using the workaround or try to find the underlying issue at a later time.

Thank you again for your help!

**Comment by ErikEJ** [comment]
@sunnylarr which build are you testing with??

**Comment by ErikEJ** [comment]
@sunnylarr Ping?

**Comment by sunnylarr** [comment]
I tested with v2.6.459 which was the latest build at that time. The project was upgraded to EF Core 8 as well.
![image](https://github.com/user-attachments/assets/b1300479-00d2-44df-90f0-23f2408d4698)

**Comment by ErikEJ** [comment]
@sunnylarr Hmm.. the thing is, VS has no influence at all on the t4 processing here. Could you try with .467 or later?
