### ISSUE TITLE
Too many models generated

### ISSUE THREAD

**Issue by MauroVevy** [ErikEJ/EFCorePowerTools#2849]
Hi Erik
After a long time I returned to use your PowerTools and I found a curious problem.
If the table configuration in the `efcpt-config.json` file does not contain any definition, even if the tag `exclusionwildcard: "*` exists, the tool generates models and related context for all the tables in my database (4259 elements)

If I add only one definition for a table, your tool generates only one model and the related context.

This is a working configuration

```
{
  "$schema": "https://raw.githubusercontent.com/ErikEJ/EFCorePowerTools/master/samples/efcpt-schema.json",
  "code-generation": {
    "enable-on-configuring": false,
    "generate-mermaid-diagram": false,
    "merge-dacpacs": false,
    "refresh-object-lists": false,
    "remove-defaultsql-from-bool-properties": false,
    "soft-delete-obsolete-files": true,
    "t4-template-path": null,
    "type": "all",
    "use-alternate-stored-procedure-resultset-discovery": false,
    "use-data-annotations": false,
    "use-database-names": false,
    "use-decimal-data-annotation-for-sproc-results": true,
    "use-inflector": true,
    "use-legacy-inflector": false,
    "use-many-to-many-entity": false,
    "use-nullable-reference-types": true,
    "use-prefix-navigation-naming": false,
    "use-t4": false
  },
  "file-layout": {
    "output-dbcontext-path": "Context",
    "output-path": "Models",
    "split-dbcontext-preview": true
  },
  "functions": [
    {
      "exclusionWildcard": "*"
    },
    {
      "name": "[dbo].[FN_VEVY_OC_SitOrdiniClienti]",
      "exclude": false
    }
  ],
  "names": {
    "dbcontext-name": "FluentisContext",
    "dbcontext-namespace": "SourceContext",
    "model-namespace": "SourceModels",
    "root-namespace": "DataExtractor"
  },
  "stored-procedures": [
    {
      "exclusionWildcard": "*"
    }
  ],
  "tables": [
    {
      "exclusionWildcard": "*"
    },
    {
      "name": "[dbo].[MG_AnaArt]",
      "exclude": false,
      "excludedColumns": [
        "MGAA_MBSC_Id",
        "MGAA_MBDV_Id",
        "MGAA_Descr2",
      ]
    }
  ],
  "views": [
    {
      "exclusionWildcard": "*"
    }
  ]
}
```

This version generates models for all my tables, while it correctly generates the model only for the function `FN_VEVY_OC_SitOrdiniClienti`

```
{
  "$schema": "https://raw.githubusercontent.com/ErikEJ/EFCorePowerTools/master/samples/efcpt-schema.json",
  "code-generation": {
    "enable-on-configuring": false,
    "generate-mermaid-diagram": false,
    "merge-dacpacs": false,
    "refresh-object-lists": false,
    "remove-defaultsql-from-bool-properties": false,
    "soft-delete-obsolete-files": true,
    "t4-template-path": null,
    "type": "all",
    "use-alternate-stored-procedure-resultset-discovery": false,
    "use-data-annotations": false,
    "use-database-names": false,
    "use-decimal-data-annotation-for-sproc-results": true,
    "use-inflector": true,
    "use-legacy-inflector": false,
    "use-many-to-many-entity": false,
    "use-nullable-reference-types": true,
    "use-prefix-navigation-naming": false,
    "use-t4": false
  },
  "file-layout": {
    "output-dbcontext-path": "Context",
    "output-path": "Models",
    "split-dbcontext-preview": true
  },
  "functions": [
    {
      "exclusionWildcard": "*"
    },
    {
      "name": "[dbo].[FN_VEVY_OC_SitOrdiniClienti]",
      "exclude": false
    }
  ],
  "names": {
    "dbcontext-name": "FluentisContext",
    "dbcontext-namespace": "SourceContext",
    "model-namespace": "SourceModels",
    "root-namespace": "DataExtractor"
  },
  "stored-procedures": [
    {
      "exclusionWildcard": "*"
    }
  ],
  "tables": [
    {
      "exclusionWildcard": "*"
    }
  ],
  "views": [
    {
      "exclusionWildcard": "*"
    }
  ]
}
```

**Comment by ErikEJ** [comment]
Which CLI version?

**Comment by MauroVevy** [comment]
efcpt.8 8.1

**Comment by ErikEJ** [comment]
Please run efcpt --help

**Comment by ErikEJ** [comment]
@MauroVevy Thanks, I will have a look, this looks like a bug!

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest nightly build], would be grateful if you could try it out.

**Comment by MauroVevy** [comment]
Using the version `efcpt.8 8.1.761+89aaa294b4d3c31bd26fb48129b90afb6b9ac1e5`

with this efcpt-config.json I still have the same problem.

```
{
  "$schema": "https://raw.githubusercontent.com/ErikEJ/EFCorePowerTools/master/samples/efcpt-schema.json",
  "code-generation": {
    "enable-on-configuring": false,
    "generate-mermaid-diagram": false,
    "merge-dacpacs": false,
    "refresh-object-lists": false,
    "remove-defaultsql-from-bool-properties": false,
    "soft-delete-obsolete-files": true,
    "t4-template-path": null,
    "type": "all",
    "use-alternate-stored-procedure-resultset-discovery": false,
    "use-data-annotations": false,
    "use-database-names": false,
    "use-decimal-data-annotation-for-sproc-results": true,
    "use-inflector": true,
    "use-legacy-inflector": false,
    "use-many-to-many-entity": false,
    "use-nullable-reference-types": true,
    "use-prefix-navigation-naming": false,
    "use-t4": false
  },
  "file-layout": {
    "output-dbcontext-path": "Context",
    "output-path": "Models",
    "split-dbcontext-preview": true
  },
  "functions": [
    {
      "exclusionWildcard": "*"
    },
    {
      "name": "[dbo].[FN_OC_SitOrdiniClienti]",
      "exclude": false
    }
  ],
  "names": {
    "dbcontext-name": "FluContext",
    "dbcontext-namespace": "SourceContext",
    "model-namespace": "SourceModels",
    "root-namespace": "DataExtractor"
  },
  "stored-procedures": [
    {
      "exclusionWildcard": "*"
    }
  ],
  "tables": [
    {
      "exclusionWildcard": "*"
    }
  ],
  "views": [
    {
      "exclusionWildcard": "*"
    }
  ]
}
```

**Comment by ErikEJ** [comment]
@MauroVevy That version is not the latest!

`dotnet tool install --global ErikEJ.EFCorePowerTools.Cli --version 8.1.770-nightly`

**Comment by MauroVevy** [comment]
With this version, you have solved both problems.
Thanks
