### ISSUE TITLE
How to make EF Core Power Tools generate HasDefaultValue for numeric columns in PostgreSQL?

### ISSUE THREAD

**Issue by netcorefan** [ErikEJ/EFCorePowerTools#2991]
### Question

Hi there,

How do I configure reverse engineering in EF Core Power Tools so that it generates HasDefaultValue for numeric columns with defaults in PostgreSQL?

Thanks a lot for your help!

Best regards,

### EF Core Power Tools version

2.6.999

### Database provider

Npgsql.EntityFrameworkCore.PostgreSQL

### Target framework

.NET 8.0

### IDE

Visual Studio 2022 17.13.7

### Do you use T4 templates?

No

### Do you use Handlebars templates?

No

### Is a SQL Server .dacpac / Database project used?

No

**Comment by ErikEJ** [comment]
Please provide a runnable CREATE script, the generated code and the expected code.

**Comment by ErikEJ** [comment]
The "integer" issue looks like a bug in the provider

https://github.com/npgsql/efcore.pg/blob/main/src%2FEFCore.PG%2FScaffolding%2FInternal%2FNpgsqlDatabaseModelFactory.cs#L1260 

Suggest you create an issue in the npgsql repo

@roji FYI

**Comment by roji** [comment]
Thanks, yeah - back when I implemented value parsing for scaffolding I only did it for bool and integer types (https://github.com/npgsql/efcore.pg/issues/2761). Opened https://github.com/npgsql/efcore.pg/issues/3540 and submitted a PR for float/double/decimal as well (there are still many other PG types but I'll handle those as requests come in).

**Comment by ErikEJ** [comment]
@roji Cool, but I think you missed "integer" with a default of 0 on line 1264

**Comment by roji** [comment]
How so? Line 1264 has PostgreSQL internal/system type names: int4 is integer, int2 is smallint, etc.

**Comment by ErikEJ** [comment]
@roji How does that explain this bug?

amount integer NOT NULL default 0

entity.Property(e => e.Id) .ValueGeneratedNever() .HasColumnName("id"); entity.Property(e => e.Amount) .HasDefaultValue(0) .HasColumnName("amount");

**Comment by roji** [comment]
I looked into it, and the provider was indeed out of sync with the way things work in the latest versions. This wasn't about a missing "integer": the responsibility of identifying zero (or DefaultValue which is the same as the CLR default) was moved out of the database model factory altogether (see https://github.com/dotnet/efcore/pull/30927) - the only responsibility the database model factory has is to parse out the CLR default value if it can, and leave the DefaultValueSql as it is, later common logic kicks in and does the right thing.

Submitted https://github.com/npgsql/efcore.pg/pull/3543 to fix this.

**Comment by ErikEJ** [comment]
@netcorefan So it looks like these Npgsql scaffolding issues will be fixed in a future release of the provider.
