### ISSUE TITLE
EF Core Power Tools version: Version 2.3.81.0 - Reverse Engineering error

### ISSUE THREAD

**Issue by smatvienko** [ErikEJ/EFCorePowerTools#305]
I used the previous version for  a year , it was working great!  Since I have  moved to net core 3.0  I just tried the new version and found an issue.

I used
[ErrorMessage.txt](https://github.com/ErikEJ/EFCorePowerTools/files/3852113/ErrorMessage.txt)
 Reverse Engineering tool ,  checked "Core 3.0" box  and got an error :
System.InvalidOperationException: The foreign key {'CompanyId'} cannot be added to the entity type 'UserAccount' because a foreign key on the same properties already exists on entity type 'UserAccount' and also targets the key {'Id'} on 'Company'.  When I repeat it  with unchecked box "Core 3.0" and I don't have any error.

Error message is attached.

I have very simple user account table with companyId foreign key.

Any help will be greatly appreciated.

Thanks in advance.

Sergey

### Further technical details

EF Core Power Tools version: Version 2.3.81.0

Data Base -  SQL Server 2016

Visual Studio version:  Visual Studio 2019 16.3.9

**Comment by ErikEJ** [comment]
Seems like you have 2 foreign keys the same in your dB - drop on of them

**Comment by smatvienko** [comment]
Hello Erik,

Thank you for the prompt response. You are a genius. I even had 3 the same
foreign keys constraint. Your application is catching this error, but MS
Sql Server is not.
Your application generates everything now, but VS compilator  gave me
another errors like this:

>UserAccount.cs(89,33,89,40): error CS0120: An object reference is required
for the non-static field, method, or property 'UserAccount.Company'
1>UserAccount.cs(95,33,95,40): error CS0120: An object reference is
required for the non-static field, method, or property 'UserAccount.Company'

lines 89-90
 [InverseProperty(nameof(Company.CreatedByNavigation))]
  public virtual ICollection<Company> CompanyCreatedByNavigations { get;
set; }


  lines 95-96
 [InverseProperty(nameof(Company.UpdatedByNavigation))]
 public virtual ICollection<Company> CompanyUpdatedByNavigations { get;
set; }

In the most another classes this your new construction works but for some
reason it does not work in several places

I changed it to

  [InverseProperty("CompanyCreatedByNavigation")] and
   [InverseProperty("CompanyUpdatedByNavigation")]

It compiles now but I am not sure if it is correct.

Please advise.

Sergey

**Comment by ErikEJ** [comment]
This issue is a known EF Core bug, I think it is fixed in 3.1 (which I will be using soon) @bricelam

**Comment by smatvienko** [comment]
Thank you.  Unfortunately I can't wait for 3.1. Could you please give me advice -  if there is a work around or it's better to use the previous version of your tool.

Thank you in advance.

**Comment by ErikEJ** [comment]
Your manual changes are a workaround, let's wait to hear comments from @bricelam

**Comment by smatvienko** [comment]
Thank you. And just by the way. Your application still has a small bug in a
new version. Sql server "bit"  column  it converts to "bool?" doesn't
matter if the column is nullable or not.
Except this  you made a great application.

**Comment by ErikEJ** [comment]
I think it is because your not nullable bit column has an unnecessary default value?

**Comment by smatvienko** [comment]
Yes, you are right again! I usually put a default value where it is
possible if  a column does not allows null. But  unfortunately during the
most times it is  useful.

Thank you very much for your help. I really appreciate it. Have a great
weekend!

Sergey

**Comment by ErikEJ** [comment]
Closing this, and created #307 to remind me about the fixes in 3.1

**Comment by bricelam** [comment]
Yes, we fixed the bad `nameof` syntax in 3.1

**Comment by smatvienko** [comment]
Thank you for  the prompt response. I am looking forward to a 3.1 release.

**Comment by DrtyByt** [comment]
Looks like this is still an issue in 5.0. I did NOT see the issue in the 6.0 preview version though.

**Comment by ErikEJ** [comment]
@DrtyByt Correct, this was actually not fixed until EF Core 6.
