### ISSUE TITLE
Pass UseSpatial when scaffolding from dacpac

### ISSUE THREAD

**Issue by m0a0k0s** [ErikEJ/EFCorePowerTools#3244]
### Question

When scaffolding from command line with dacpac nuget package, I'm getting errors
Could not find type mapping for column '....FromGeoPoint' with data type 'geography'. Skipping column.
`dotnet ef dbcontext scaffold "....dacpac" ErikEJ.EntityFrameworkCore.SqlServer.Dacpac --use-database-names --force --no-onconfiguring --output-dir "Model" --context-dir "DatabaseContext"`
Scaffolding directly from database works:
`dotnet ef dbcontext scaffold "data source=..;initial catalog=...;persist security info=True;user id=...;MultipleActiveResultSets=True;App=EntityFramework;TrustServerCertificate=True" Microsoft.EntityFrameworkCore.SqlServer --use-database-names --force --no-onconfiguring --output-dir "Model" --context-dir "DatabaseContext"`
As I understand I need to pass UseSpatial flag, I tried with putting efpt.config.json in project folder with 
```
{
  "UseSpatial": true
}
```
but it didn't help

### Target framework

.Net 9.0

### Do you use T4 templates?

None

### Do you use Handlebars templates?

None

### Is a SQL Server .dacpac / Database project used?

None

**Comment by ErikEJ** [comment]
@m0a0k0s For a full featured .dacpac reverse engineer experience, use the EF Core Power Tools CLI.

**Comment by m0a0k0s** [comment]
It's a full-scale EF Core Power Tools that brings its own range of issues - it can’t load 3rd party assembly in t4 templates, and some issues with field renaming.

Is there any way to change it to load only spatial types? The same scaffolding process loads them from the host in a later step.

```
error: error CS0006: Metadata file 'EntityFrameworkRuler.Design' could not be found

error: Microsoft.EntityFrameworkCore.Design.OperationException: Processing 'CodeTemplates\EFCore\DbContext.t4' failed.
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.TextTemplatingModelGenerator.HandleErrors(TextTemplatingEngineHost host)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.TextTemplatingModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
   at RevEng.Core.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions, Boolean removeNullableBoolDefaults, Boolean excludeNavigations, Boolean dbContextOnly, Boolean 
entitiesOnly, Boolean useSchemaFolders, Boolean useSchemaNamespaces) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.80\ReverseEngineerScaffolder.cs:line 500
   at RevEng.Core.ReverseEngineerScaffolder.GenerateDbContext(ReverseEngineerCommandOptions options, List`1 schemas, String outputContextDir, String modelNamespace, String contextNamespace, String projectPath, String outputPath, String rootNameSpace) in 
D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.80\ReverseEngineerScaffolder.cs:line 93
   at RevEng.Core.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions options) in D:\a\EFCorePowerTools\EFCorePowerTools\src\Core\RevEng.Core.80\ReverseEngineerRunner.cs:line 92
```

**Comment by ErikEJ** [comment]
Maybe i just need to add a reference to the spatial SQL Server provider. Let me give that a try

**Comment by ErikEJ** [comment]
Maybe i just need to add a reference to the spatial SQL Server provider. Let me give that a try

**Comment by ErikEJ** [comment]
@m0a0k0s I have published new package versions (preview)

**Comment by m0a0k0s** [comment]
columns are still not created with the same warning. I think it missing spatial registration in SqlServerDacpacDesignTimeServices
```
var spatial = new SqlServerNetTopologySuiteDesignTimeServices();
spatial.ConfigureDesignTimeServices(serviceCollection);
```

**Comment by ErikEJ** [comment]
@m0a0k0s New packages are up, thanks for the tip! (also added hierarchyid support)

**Comment by m0a0k0s** [comment]
It works, thank you

**Comment by ErikEJ** [comment]
Wonderful, thanks for your contribution
