### ISSUE TITLE
NullReferenceException when using Reverse Engineering with Handlebars

### ISSUE THREAD

**Issue by hanselsen** [ErikEJ/EFCorePowerTools#463]
I have this configuration and I already have the `CodeTemplates` folder in my project.

![image](https://user-images.githubusercontent.com/1150323/90238353-1a531f00-de26-11ea-9d0e-b17f7164491d.png)

Using VS2019, MySQL 8 and EFCorePowerTools 2.4

And I get this result:

```
System.Exception: Reverse engineer error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpDbContextGenerator.GenerateRelationship(IForeignKey foreignKey, Boolean useDataAnnotations, IndentedStringBuilder sb)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpDbContextGenerator.GenerateEntityType(IEntityType entityType, Boolean useDataAnnotations, IndentedStringBuilder sb)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpDbContextGenerator.GenerateOnModelCreating(IModel model, Boolean useDataAnnotations)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpDbContextGenerator.GenerateClass(IModel model, String contextName, String connectionString, Boolean useDataAnnotations, Boolean suppressConnectionStringWarning)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpDbContextGenerator.WriteCode(IModel model, String contextName, String connectionString, String contextNamespace, String modelNamespace, Boolean useDataAnnotations, Boolean suppressConnectionStringWarning)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at ReverseEngineer20.ReverseEngineer.ReverseEngineerRunner.GenerateFiles(ReverseEngineerCommandOptions reverseEngineerOptions) in C:\Code\EFCorePowerTools\src\GUI\RevEng.Core\ReverseEngineerRunner.cs:line 89
   at efreveng.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efreveng\Program.cs:line 57

   at EFCorePowerTools.Handlers.ReverseEngineer.ResultDeserializer.BuildResult(String output) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\ResultDeserializer.cs:line 27
   at ReverseEngineer20.ReverseEngineer.EfRevEngLauncher.GetOutput() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineer\EfRevEngLauncher.cs:line 81
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.LaunchExternalRunner(ReverseEngineerOptions options, Boolean useEFCore5) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 381
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 225
```

Any ideas?

**Comment by ErikEJ** [comment]
Maybe #450 ?

**Comment by hanselsen** [comment]
I removed the `CodeTemplates` folder from the File Explorer and ran the generator again. Still returns the same error.

**Comment by ErikEJ** [comment]
No idea - let's ask @tonysneed

**Comment by tonysneed** [comment]
Let me check.

**Comment by tonysneed** [comment]
I have not been able to replicate the error. Here is the version of EFCPT I am using: 2.4.157.0

I have reverse engineered both SQL Server and MySQL databases, checking the option to Customize Code using Handlebars templates. In both cases there were no errors at all.

@hanselsen What is the exact version of EFCPT you are using?

**Comment by ErikEJ** [comment]
We probably need your schema!

**Comment by hanselsen** [comment]
Is there a way I can send it to you privately?

**Comment by ErikEJ** [comment]
Sure, email me ejlskov at Hotmail dot com

**Comment by hanselsen** [comment]
@tonysneed  I also use 2.4.157. I mailed @ErikEJ my schema.

**Comment by ErikEJ** [comment]
@hanselsen  I just realize you are using MySQL - most likely an issue with your provider - are you using Pomelo?

**Comment by hanselsen** [comment]
Yes. It's Pomelo 3.2.1

**Comment by ErikEJ** [comment]
@hanselsen Look like a Handlebars bug - see https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/136

**Comment by ErikEJ** [comment]
Should be fixed in latest daily build, please try it out and let me know.

**Comment by hanselsen** [comment]
I now have version 2.4.163, but it is still showing the same NRE.
I did delete the CodeTemplates folder from the disk again.

**Comment by ErikEJ** [comment]
I think you need to verify the bug, using Handlebars from the command line as described here: https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#usage and if you are able to do so, file a bug in the Handlebars repo.

**Comment by hanselsen** [comment]
Alright. Updating the Handlebars package to 3.8.3 did the trick.
Thanks for the support! 👌

**Comment by ErikEJ** [comment]
@hanselsen I do not understand - the latest Power Tools build also uses 3.8.3 !?

**Comment by hanselsen** [comment]
Could it be that it used the installed Nuget package (so, old) instead of the package that is bundled with Power Tools?

**Comment by ErikEJ** [comment]
What is installed in your project and by Power Tools are two completely different things! Power Tools does not run your app.

**Comment by hanselsen** [comment]
I would think so, but after updating the Nuget package to 3.8.3, it worked...

**Comment by hanselsen** [comment]
Right now, I have

```
Version 2.4.163.0

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes
```

But it stopped working again... this is getting frustrating. 
Is there a way for me to debug it myself?

**Comment by ErikEJ** [comment]
Maybe you still have the old version of the extension hanging around, 
shut down and restart any VS instances and check %localappdata%\Microsoft\VisualStudio folder (and subfolders)

**Comment by hanselsen** [comment]
I cleared the cache. Reinstalled the Power Tools and still the NRE.
I also tried it using the CLI as instructed here https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#usage and that works. Also the template files.

In combination with the Power Tools however, nothing.

**Comment by ErikEJ** [comment]
I could have made a mistake when I merged - will rebuild the tooling a prep a newer Power Tools build

**Comment by ErikEJ** [comment]
Update on the way! (Build .164  or newer)

**Comment by ErikEJ** [comment]
Once installed, you can locate EntityFrameworkCore.Scaffolding.Handlebars.dll and verify the Product version from File Properties

**Comment by hanselsen** [comment]
Awesome! It works. Thanks for the great tool!
