### ISSUE TITLE
Reverse Engineer assigns wrong schema to table valued parameter from the database

### ISSUE THREAD

**Issue by bhroberts52** [ErikEJ/EFCorePowerTools#618]
Situation:
I have a stored procedure that takes a table-valued parameter as input. The stored procedure and the table-valued parameter do not share the same schema. The EF Power Tool assigns the wrong schema to the table-valued in the XXContextProcedures class.  

Here is a snippet of code from the XXContextProcedures class.  The error is in the schema of the type:

 ```
var parameterCategoryIDs = new SqlParameter
            {
                ParameterName = "CategoryIDs",
                Value = CategoryIDs ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Structured,
                TypeName = "[supplies].[TVP_Id]",
            };
```

The stored procedure's schema is [supplies], but the schema of [TVP_Id] schema is [dbo] in the database.  I have to do find and replace after each time I run a reverse engineer in order to replace **[supplies].[TVP_Id]** with **[dbo].[TVP_Id]**.  

Otherwise, I really love the tool! 

If you are unable to verify the bug I will supply SQL code to reproduce the error.

### Further technical details
EF Core Power Tools version: 2.5

Database engine: Azure SQL Database

Visual Studio version: 2019 Preview version 16.9.0 Preview 1.0

**Comment by ErikEJ** [comment]
Happy to help, but need repro SQL code, thanks

**Comment by bhroberts52** [comment]
I am attaching a minimal example SQL Script and NET5 solution.  The error is in LocationDbContextProcedures.cs on line 34.  I commented out that line and replaced it with what the tool should generate for the code to work. Thanks.
[CreateDatabaseScriptAndNet5Solution.zip](https://github.com/ErikEJ/EFCorePowerTools/files/5609587/CreateDatabaseScriptAndNet5Solution.zip)

**Comment by ErikEJ** [comment]
Thanks for reporting this, fixed in latest daily build

**Comment by bhroberts52** [comment]
Thank you!

**Comment by bhroberts52** [comment]
Just tried it, but I'm still seeing same issue.  Is there a delay in getting the new build through automatic updates?  (I also tried uninstalling and reinstalling through VS 2019 extensions to no avail. )  Continued thanks.

**Comment by ErikEJ** [comment]
Did you download the daily build? Link in release notes in the wiki...

**Comment by bhroberts52** [comment]
Got it!  Works now.  Thanks for the hint!
